// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
import { createId } from "./ids.js";
import type {
  ChassisSetup,
  Conditions,
  TreadTemps,
  TyrePressures,
  TyreTemps,
} from "./types.js";

export function emptyCornerPressures(): TyrePressures {
  return {
    cold: { fl: 1.0, fr: 1.0, rl: 1.0, rr: 1.0 },
    hot: { fl: null, fr: null, rl: null, rr: null },
  };
}

export function emptyTread(): TreadTemps {
  return { outside: null, middle: null, inside: null };
}

export function emptyTyreTemps(): TyreTemps {
  return {
    fl: emptyTread(),
    fr: emptyTread(),
    rl: emptyTread(),
    rr: emptyTread(),
  };
}

/** Starting points from ANGRI kart-setup: normal dry grip, ~43/57. */
export function defaultChassisSetup(): ChassisSetup {
  return {
    id: createId("setup"),
    name: "Baseline dry",
    wheelbase: "1050",
    chassisBrand: "",
    frontRideHeight: "min",
    rearRideHeight: "mid",
    frontTrack: "mid",
    rearTrack: "mid",
    frontHubLength: "mid",
    rearHubLength: "mid",
    frontHubSpacers: 1,
    toeMm: 2,
    camberMm: -1,
    caster: "mid",
    ackermann: "mid",
    axleStiffness: "medium",
    rearTorsion: "off",
    frontTorsion: "off",
    fourthTorsion: false,
    seatStruts: "one_per_side",
    sidepods: "loose",
    thirdBearing: "none",
    frontBumper: "loose",
    rearBumper: "loose",
    seatPosition: "mid",
    seatHeight: "mid",
    rainMeister: false,
    tyreType: "slick",
    tyreCompound: "unknown",
    rimMaterial: "aluminium",
    driverWeightKg: 75,
    ballastKg: 0,
    ballastForeAft: "mid",
    ballastVertical: "low",
    notes: "",
  };
}

export function defaultConditions(): Conditions {
  return {
    grip: "normal",
    wet: false,
    trackDirection: "clockwise",
    airTempC: null,
    trackTempC: null,
    targetTyreTempC: 80,
    trackId: null,
    trackName: null,
    humidityPct: null,
    pressureHpa: null,
  };
}
