// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
import { actionApplies, isBlockedByLimit, matchesGate } from "./limits.js";
import { handlingRules } from "./rules/load.js";
import type { HandlingAction } from "./rules/schema.js";
import type {
  Advice,
  AnalysisResult,
  AnalysisTraceStep,
  ChassisSetup,
  Conditions,
  Symptom,
} from "./types.js";
import { SYMPTOM_LABELS } from "./types.js";

const SOURCE = handlingRules.sources?.[0] ?? "https://www.angriracing.com/kart-setup";

function toAdvice(
  action: HandlingAction,
  setup: ChassisSetup,
  extraWhy?: string,
): Advice {
  const polarity =
    action.polarityNote && (setup.wheelbase === "950" || setup.wheelbase === "bambino")
      ? "950_may_invert"
      : undefined;
  return {
    id: action.id,
    lever: action.lever,
    direction: action.direction,
    magnitude: action.magnitude,
    title: action.title,
    why: extraWhy ? `${action.why} ${extraWhy}` : action.why,
    kbSource: SOURCE,
    kbSourceId: handlingRules.id,
    polarityNote: polarity,
    priority: action.priority,
    oneChange: true,
  };
}

function gripNote(conditions: Conditions): string | null {
  if (conditions.wet) {
    return "Wet: extra caster and a wide front are usually the first chassis moves; rain tyres first.";
  }
  if (conditions.grip === "green") {
    return "Green / low grip: more caster, ride height up, torsion and struts on are typical starting moves.";
  }
  if (conditions.grip === "rubbered") {
    return "High grip / rubbered-in: less caster, lower rear, softer rear, struts and torsion off.";
  }
  return null;
}

function gateReason(setup: ChassisSetup, action: HandlingAction): string | null {
  if (action.when && !matchesGate(setup, action.when)) {
    return "when-gate not met for this sheet";
  }
  if (action.requires && !matchesGate(setup, action.requires)) {
    return "requires-gate not met for this sheet";
  }
  if (action.skipWhen && matchesGate(setup, action.skipWhen)) {
    return "skipWhen matched — this lever is not the move on the current sheet";
  }
  return null;
}

function drivingTrace(input: {
  symptoms: Symptom[];
  first?: Advice;
  blocked: Advice[];
  skipped: string[];
  source: string;
}): AnalysisTraceStep[] {
  const steps: AnalysisTraceStep[] = [
    {
      id: "symptoms",
      label: "Symptoms",
      detail: input.symptoms.map((s) => SYMPTOM_LABELS[s]).join(", ") || "None selected",
    },
  ];
  if (input.first) {
    steps.push({
      id: "first",
      label: "Do this first",
      detail: `${input.first.title} (${input.first.id}, priority ${input.first.priority})`,
    });
    steps.push({
      id: "why",
      label: "Why",
      detail: input.first.why,
    });
    if (input.first.polarityNote === "950_may_invert") {
      steps.push({
        id: "polarity",
        label: "950 / Bambino",
        detail: "Axle polarity can invert versus 1050 literature. If this fails, try the opposite.",
      });
    }
  }
  if (input.skipped.length > 0) {
    steps.push({
      id: "skipped",
      label: "Skipped",
      detail: input.skipped.join(" · "),
    });
  }
  if (input.blocked.length > 0) {
    steps.push({
      id: "blocked",
      label: "Already at the limit",
      detail: input.blocked.map((item) => item.title).join(" · "),
    });
  }
  steps.push({ id: "source", label: "Source", detail: input.source });
  return steps;
}

export function diagnoseDriving(
  setup: ChassisSetup,
  conditions: Conditions,
  symptoms: Symptom[],
): AnalysisResult {
  const warnings: string[] = [];
  const unique = [...new Set(symptoms)];

  if (unique.length === 0) {
    return {
      kind: "driving",
      reminder: handlingRules.reminder,
      advice: [],
      blocked: [],
      warnings: ["Pick at least one handling symptom."],
      trace: drivingTrace({ symptoms: [], blocked: [], skipped: [], source: SOURCE }),
    };
  }

  if (unique.length > 1) {
    warnings.push("Several symptoms selected — still change only one lever, starting with the first card.");
  }

  const grip = gripNote(conditions);
  if (grip) warnings.push(grip);

  if (conditions.wet && setup.tyreType !== "wet") {
    warnings.push("Wet selected but the sheet still says slicks. Rain tyres first.");
  }

  const advice: Advice[] = [];
  const blocked: Advice[] = [];
  const skipped: string[] = [];

  for (const symptom of unique) {
    const rule = handlingRules.rules.find((item) => item.symptoms.includes(symptom));
    if (!rule) {
      warnings.push(`No rule encoded for ${symptom}.`);
      continue;
    }

    for (const action of rule.actions) {
      const card = toAdvice(action, setup);
      const atLimit = isBlockedByLimit(setup, action.lever, action.direction);
      if (!actionApplies(setup, action)) {
        const reason = gateReason(setup, action);
        skipped.push(`${action.id}: ${reason ?? "gate"}`);
        if (atLimit) blocked.push(card);
        continue;
      }
      if (atLimit) {
        blocked.push(card);
        skipped.push(`${action.id}: already at the recorded limit`);
        continue;
      }
      advice.push(card);
    }
  }

  advice.sort((a, b) => a.priority - b.priority || a.id.localeCompare(b.id));

  if (advice.length === 0 && blocked.length > 0) {
    warnings.push("Every listed lever is already at the recorded limit. Recheck the sheet or look at the blocked list.");
  }

  return {
    kind: "driving",
    reminder: handlingRules.reminder,
    advice,
    blocked,
    warnings,
    trace: drivingTrace({
      symptoms: unique,
      first: advice[0],
      blocked,
      skipped,
      source: SOURCE,
    }),
  };
}
