// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
import { round } from "./units.js";

const RD = 287.058;
const RV = 461.495;
const RHO_SEA = 1.225;

/** Magnus saturation vapour pressure in hPa. */
export function saturationVapourHpa(tempC: number): number {
  return 6.1078 * 10 ** ((7.5 * tempC) / (237.3 + tempC));
}

export type AirDensityInput = {
  tempC: number;
  pressureHpa: number;
  relativeHumidityPct: number;
};

export type AirDensityResult = {
  densityKgM3: number;
  relativeAirDensity: number;
  densityAltitudeM: number;
  densityAltitudeFt: number;
  vapourHpa: number;
};

export function airDensity(input: AirDensityInput): AirDensityResult {
  const tempK = input.tempC + 273.15;
  const rh = Math.min(100, Math.max(0, input.relativeHumidityPct)) / 100;
  const vapourHpa = saturationVapourHpa(input.tempC) * rh;
  const dryHpa = Math.max(0, input.pressureHpa - vapourHpa);
  const densityKgM3 =
    (dryHpa * 100) / (RD * tempK) + (vapourHpa * 100) / (RV * tempK);
  const relativeAirDensity = densityKgM3 / RHO_SEA;
  const densityAltitudeM = 44330.77 * (1 - relativeAirDensity ** 0.234969);
  return {
    densityKgM3: round(densityKgM3, 4),
    relativeAirDensity: round(relativeAirDensity, 4),
    densityAltitudeM: round(densityAltitudeM, 0),
    densityAltitudeFt: round(densityAltitudeM * 3.28084, 0),
    vapourHpa: round(vapourHpa, 2),
  };
}
