// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
import { wetGearingDelta } from "../wetPreset.js";
import { round } from "./units.js";

export type GearingInput = {
  frontTeeth: number;
  rearTeeth: number;
  /** Rolling circumference of the driven tyre, mm. */
  tyreCircumferenceMm: number;
  engineRpm?: number;
};

export type GearingResult = {
  ratio: number;
  rolloutMm: number;
  speedAtRpmKmh: number | null;
  equivalentSmaller: { front: number; rear: number } | null;
  wetSuggestion: string;
  summary: string;
  kbSource: string;
};

export function gearing(input: GearingInput): GearingResult {
  const front = Math.max(1, input.frontTeeth);
  const rear = Math.max(1, input.rearTeeth);
  const ratio = rear / front;
  const rolloutMm = input.tyreCircumferenceMm / ratio;
  const rpm = input.engineRpm;
  const speedAtRpmKmh =
    typeof rpm === "number" && rpm > 0
      ? ((rpm * (front / rear) * input.tyreCircumferenceMm) / 1000 / 1000) * 60
      : null;

  let equivalentSmaller: GearingResult["equivalentSmaller"] = null;
  if (front > 8 && rear > 8) {
    equivalentSmaller = { front: front - 1, rear: Math.round(((front - 1) * rear) / front) };
  }

  const wetDelta = wetGearingDelta();
  return {
    ratio: round(ratio, 3),
    rolloutMm: round(rolloutMm, 1),
    speedAtRpmKmh: speedAtRpmKmh == null ? null : round(speedAtRpmKmh, 1),
    equivalentSmaller,
    wetSuggestion: `Wet + rain tyres: +${wetDelta} or more rear teeth (try ${rear + wetDelta}). Drop teeth as it dries. Do not hide a handling problem with extra teeth.`,
    summary: `Ratio ${round(ratio, 3)}:1. More rear teeth = more acceleration, less top speed.`,
    kbSource: "https://www.angriracing.com/chains-sprockets-and-ratios",
  };
}
