// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
export function barToPsi(bar: number): number {
  return bar * 14.503773773;
}

export function psiToBar(psi: number): number {
  return psi / 14.503773773;
}

export function cToF(c: number): number {
  return (c * 9) / 5 + 32;
}

export function fToC(f: number): number {
  return ((f - 32) * 5) / 9;
}

export function kgToLb(kg: number): number {
  return kg * 2.2046226218;
}

export function lbToKg(lb: number): number {
  return lb / 2.2046226218;
}

export function mmToIn(mm: number): number {
  return mm / 25.4;
}

export function inToMm(inches: number): number {
  return inches * 25.4;
}

export function hpaToInHg(hpa: number): number {
  return hpa * 0.0295299830714;
}

export function inHgToHpa(inHg: number): number {
  return inHg / 0.0295299830714;
}

export function litresToUsGal(l: number): number {
  return l * 0.26417205236;
}

export function usGalToLitres(gal: number): number {
  return gal / 0.26417205236;
}

export function round(value: number, digits = 2): number {
  const f = 10 ** digits;
  return Math.round(value * f) / f;
}
