// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
import { pressureRules } from "./rules/load.js";
import type { CompoundWindow } from "./rules/schema.js";
import type {
  Advice,
  AnalysisResult,
  ChassisSetup,
  Conditions,
  TyreCorner,
  TyrePressures,
} from "./types.js";
import { TYRE_CORNERS } from "./types.js";

const SOURCE = pressureRules.sources?.[0] ?? "https://www.angriracing.com/tyre-setup";

/** Cited cold-pressure window for the setup's compound, or null when unknown. */
export function compoundWindow(setup: ChassisSetup): CompoundWindow | null {
  return pressureRules.compounds?.[setup.tyreCompound] ?? null;
}

function advice(partial: Omit<Advice, "oneChange" | "kbSource" | "kbSourceId">): Advice {
  return {
    ...partial,
    kbSource: SOURCE,
    kbSourceId: pressureRules.id,
    oneChange: true,
  };
}

function expectedRise(setup: ChassisSetup): number {
  return setup.rimMaterial === "magnesium"
    ? pressureRules.rise.magnesiumBar
    : pressureRules.rise.aluminiumBar;
}

function filled(pressures: TyrePressures, key: "cold" | "hot"): boolean {
  return TYRE_CORNERS.every((corner) => {
    const value = pressures[key][corner];
    return typeof value === "number" && Number.isFinite(value) && value > 0;
  });
}

function avg(pressures: TyrePressures, key: "cold" | "hot"): number {
  const values = TYRE_CORNERS.map((c) => pressures[key][c] as number);
  return values.reduce((a, b) => a + b, 0) / values.length;
}

function spread(pressures: TyrePressures, key: "cold" | "hot"): number {
  const values = TYRE_CORNERS.map((c) => pressures[key][c] as number);
  return Math.max(...values) - Math.min(...values);
}

export function analyzePressures(
  setup: ChassisSetup,
  conditions: Conditions,
  pressures: TyrePressures,
): AnalysisResult {
  const warnings: string[] = [];
  const adviceList: Advice[] = [];

  if (!filled(pressures, "cold")) {
    return {
      kind: "pressure",
      reminder: "Record cold pressures on all four tyres before the run.",
      advice: [],
      blocked: [],
      warnings: ["Cold pressures are incomplete."],
    };
  }

  if (!filled(pressures, "hot")) {
    return {
      kind: "pressure",
      reminder: "Record hot pressures as soon as the kart stops.",
      advice: [],
      blocked: [],
      warnings: ["Hot pressures are incomplete. Log them immediately after the run."],
    };
  }

  const { min, max, start } = pressureRules.windowBar;
  const step = pressureRules.stepBar;
  const hotAvg = avg(pressures, "hot");
  const coldAvg = avg(pressures, "cold");
  const riseAvg = hotAvg - coldAvg;
  const expect = expectedRise(setup);
  const compound = compoundWindow(setup);

  warnings.push(pressureRules.rise.note);
  if (compound && compound.type !== setup.tyreType) {
    warnings.push(
      `Compound/tyre mismatch: sheet says ${setup.tyreType} tyres but the selected compound (${compound.label}) is a ${compound.type}. Fix the sheet before trusting pressure advice.`,
    );
  }
  if (compound) {
    const lo = compound.coldBar.min;
    const hi = compound.coldBar.max;
    if (coldAvg > hi + 0.05) {
      adviceList.push(
        advice({
          id: "cold_above_compound",
          lever: "pressures",
          direction: "decrease",
          magnitude: `cold ${coldAvg.toFixed(2)} bar vs ${lo.toFixed(2)}–${hi.toFixed(2)}`,
          title: `Cold pressures above the ${compound.label} window`,
          why: `Cited cold window for ${compound.label} is ${lo.toFixed(2)}–${hi.toFixed(2)} bar (${compound.coldPsi.min}–${compound.coldPsi.max} psi). Source: ${compound.source}. Optimum varies with track and weather — verify with hot readings and the pyrometer.`,
          priority: 1,
        }),
      );
    } else if (coldAvg < lo - 0.05) {
      adviceList.push(
        advice({
          id: "cold_below_compound",
          lever: "pressures",
          direction: "increase",
          magnitude: `cold ${coldAvg.toFixed(2)} bar vs ${lo.toFixed(2)}–${hi.toFixed(2)}`,
          title: `Cold pressures below the ${compound.label} window`,
          why: `Cited cold window for ${compound.label} is ${lo.toFixed(2)}–${hi.toFixed(2)} bar (${compound.coldPsi.min}–${compound.coldPsi.max} psi). Source: ${compound.source}. Under-pressure tyres never reach temperature.`,
          priority: 1,
        }),
      );
    }
  }
  if (setup.rimMaterial === "magnesium") {
    warnings.push("Magnesium rims heat faster — expect a larger cold-to-hot rise; start a little lower than aluminium.");
  }
  if (conditions.wet) {
    warnings.push("Wets struggle to temperature. Higher pressures are normal; still stay inside the class window.");
  }

  // Hot window: generic ANGRI band, or compound cold window + expected rise when a compound is set.
  const hotMin = compound ? compound.coldBar.min + expect - 0.05 : min;
  const hotMax = compound ? compound.coldBar.max + expect + 0.1 : max;
  const hotStart = compound ? (hotMin + hotMax) / 2 : start;
  const windowLabel = compound
    ? `${compound.label} cold window + expected rise`
    : `ANGRI ${min}–${max} bar window`;

  if (hotAvg > hotMax) {
    const delta = Math.max(step, Math.round((hotAvg - hotStart) * 10) / 10);
    adviceList.push(
      advice({
        id: "hot_high",
        lever: "pressures",
        direction: "decrease",
        magnitude: `−${step.toFixed(1)} bar (hot average ${hotAvg.toFixed(2)} bar)`,
        title: "Hot pressures above the working window",
        why: `${windowLabel}: hot should land near ${hotMin.toFixed(2)}–${hotMax.toFixed(2)} bar. Hot average is ${hotAvg.toFixed(2)} bar. Drop cold by about ${delta.toFixed(1)} bar next run.`,
        priority: 1,
      }),
    );
  } else if (hotAvg < hotMin) {
    adviceList.push(
      advice({
        id: "hot_low",
        lever: "pressures",
        direction: "increase",
        magnitude: `+${step.toFixed(1)} bar (hot average ${hotAvg.toFixed(2)} bar)`,
        title: "Hot pressures below the working window",
        why: `${windowLabel}: hot average is ${hotAvg.toFixed(2)} bar, under ${hotMin.toFixed(2)} bar. Raise cold by ${step.toFixed(1)} bar. Wets and green tracks may still read low if the tyre is not working.`,
        priority: 1,
      }),
    );
  }

  if (riseAvg > expect + 0.08) {
    adviceList.push(
      advice({
        id: "rise_high",
        lever: "pressures",
        direction: "decrease",
        magnitude: `−${step.toFixed(1)} bar cold`,
        title: "Cold-to-hot rise is large",
        why: `Average rise is ${riseAvg.toFixed(2)} bar (expected ~${expect.toFixed(2)} bar on ${setup.rimMaterial} rims). Start lower so hot lands near ${start.toFixed(1)} bar.`,
        priority: 2,
      }),
    );
  } else if (riseAvg < Math.max(0.04, expect - 0.1)) {
    adviceList.push(
      advice({
        id: "rise_low",
        lever: "pressures",
        direction: "check",
        title: "Cold-to-hot rise is small",
        why: `Average rise is only ${riseAvg.toFixed(2)} bar. The tyre may not be in the working band, the run was too short, or cold was already high.`,
        priority: 3,
      }),
    );
  }

  const hotSpread = spread(pressures, "hot");
  if (hotSpread > pressureRules.evenToleranceBar * 3) {
    adviceList.push(
      advice({
        id: "uneven_hot",
        lever: "chassis_check",
        direction: "check",
        magnitude: `${hotSpread.toFixed(2)} bar spread`,
        title: "Hot pressures are uneven",
        why: "A large left/right or front/rear pressure split after a run is a chassis, stagger, or leak check — not a single-corner camber chase.",
        priority: 1,
      }),
    );
  }

  const rearHot = ((pressures.hot.rl as number) + (pressures.hot.rr as number)) / 2;
  const frontHot = ((pressures.hot.fl as number) + (pressures.hot.fr as number)) / 2;
  if (rearHot - frontHot > 0.15) {
    adviceList.push(
      advice({
        id: "rear_hotter",
        lever: "rear_pressure",
        direction: "decrease",
        magnitude: `−${step.toFixed(1)} bar rear`,
        title: "Rear hot pressures higher than front",
        why: "Bring the rear down a step so front and rear work in the same window, then read tyre temps.",
        priority: 4,
      }),
    );
  } else if (frontHot - rearHot > 0.15) {
    adviceList.push(
      advice({
        id: "front_hotter",
        lever: "front_pressure",
        direction: "decrease",
        magnitude: `−${step.toFixed(1)} bar front`,
        title: "Front hot pressures higher than rear",
        why: "Bring the front down a step, then confirm with a pyrometer.",
        priority: 4,
      }),
    );
  }

  if (adviceList.length === 0) {
    adviceList.push(
      advice({
        id: "pressures_ok",
        lever: "pressures",
        direction: "check",
        title: "Pressures look in the window",
        why: `Hot average ${hotAvg.toFixed(2)} bar, rise ${riseAvg.toFixed(2)} bar. Next use the temperature analysis. One change at a time.`,
        priority: 10,
      }),
    );
  }

  adviceList.sort((a, b) => a.priority - b.priority);
  return {
    kind: "pressure",
    reminder: compound
      ? `${compound.label}: cold ${compound.coldBar.min.toFixed(2)}–${compound.coldBar.max.toFixed(2)} bar (${compound.coldPsi.min}–${compound.coldPsi.max} psi). One change at a time.`
      : `Working window cited: ${min}–${max} bar. Start near ${start.toFixed(1)} bar. One change at a time.`,
    advice: adviceList,
    blocked: [],
    warnings,
  };
}

export function pressureRiseByCorner(pressures: TyrePressures): Record<TyreCorner, number | null> {
  const out = {} as Record<TyreCorner, number | null>;
  for (const corner of TYRE_CORNERS) {
    const cold = pressures.cold[corner];
    const hot = pressures.hot[corner];
    out[corner] =
      typeof cold === "number" && typeof hot === "number" ? hot - cold : null;
  }
  return out;
}
