// AUTO-GENERATED by scripts/sync-setup-engine.mjs — do not edit. Source: tools/setup-engine/src
import { airDensity, type AirDensityResult } from "./calculators/airDensity.js";
import { formatLapTime, type LoggerAnalysis, type LoggerLap } from "./logger/analyze.js";
import type { LoggerSample } from "./logger/parseCsv.js";
import type { Conditions } from "./types.js";

/**
 * Session context helpers: imported weather -> Conditions, RAD from conditions,
 * GPS fix extraction for track auto-tagging, and lap-consistency insights.
 * The app owns fetching (open-meteo) and geofence matching; this module owns
 * the maths so it stays testable outside Expo.
 */

/** Shape the app maps open-meteo's `current` block into. All fields optional. */
export type ImportedWeather = {
  airTempC?: number | null;
  humidityPct?: number | null;
  pressureHpa?: number | null;
  /** WMO weather code (open-meteo `weather_code`). */
  weatherCode?: number | null;
  windKmh?: number | null;
};

/** WMO codes that imply a wet track: drizzle 51-57, rain 61-67, showers 80-82, thunderstorms 95-99. */
export function wmoImpliesWet(code: number | null | undefined): boolean {
  if (code == null) return false;
  return (code >= 51 && code <= 67) || (code >= 80 && code <= 82) || code >= 95;
}

/**
 * Merge imported weather into Conditions without stomping user-entered values:
 * a field is only overwritten when the user has not set it (null) or when
 * `force` is passed (the "re-import" button).
 */
export function applyWeather(
  conditions: Conditions,
  weather: ImportedWeather,
  force = false,
): Conditions {
  const take = <T>(current: T | null, incoming: T | null | undefined): T | null =>
    (force || current == null) && incoming != null ? incoming : current;
  const next: Conditions = {
    ...conditions,
    airTempC: take(conditions.airTempC, weather.airTempC),
    humidityPct: take(conditions.humidityPct, weather.humidityPct),
    pressureHpa: take(conditions.pressureHpa, weather.pressureHpa),
  };
  if (wmoImpliesWet(weather.weatherCode) && !conditions.wet) {
    next.wet = force ? true : next.wet;
  }
  return next;
}

/** RAD/air-density from session conditions when temp+pressure+humidity are all present. */
export function conditionsAirDensity(conditions: Conditions): AirDensityResult | null {
  if (
    conditions.airTempC == null ||
    conditions.pressureHpa == null ||
    conditions.humidityPct == null
  ) {
    return null;
  }
  return airDensity({
    tempC: conditions.airTempC,
    pressureHpa: conditions.pressureHpa,
    relativeHumidityPct: conditions.humidityPct,
  });
}

/** First valid GPS fix in a logger file — lets the app geofence-match the upload to a track. */
export function firstGpsFix(samples: LoggerSample[]): { lat: number; lon: number } | null {
  for (const s of samples) {
    if (
      typeof s.lat === "number" &&
      typeof s.lon === "number" &&
      Number.isFinite(s.lat) &&
      Number.isFinite(s.lon) &&
      (s.lat !== 0 || s.lon !== 0)
    ) {
      return { lat: s.lat, lon: s.lon };
    }
  }
  return null;
}

export type ConsistencyInsight = {
  id: string;
  title: string;
  detail: string;
};

export type SessionConsistency = {
  lapCount: number;
  bestS: number | null;
  medianS: number | null;
  /** Spread of the middle laps (median absolute deviation, seconds). */
  madS: number | null;
  /** 0-100: how close the typical lap is to the best lap. */
  consistencyPct: number | null;
  insights: ConsistencyInsight[];
};

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

/**
 * Junior-friendly consistency read on an analysed session.
 * Consistency beats one hero lap: score = how close the median lap is to the
 * best lap (100 = every lap equals the best).
 */
export function sessionConsistency(analysis: LoggerAnalysis): SessionConsistency {
  const laps = analysis.laps;
  const times = laps.map((l) => l.timeS);
  if (times.length < 2) {
    return {
      lapCount: times.length,
      bestS: times[0] ?? null,
      medianS: times[0] ?? null,
      madS: null,
      consistencyPct: null,
      insights: [
        {
          id: "need_laps",
          title: "Need more laps",
          detail: "Two or more timed laps are needed for a consistency read.",
        },
      ],
    };
  }

  const bestS = Math.min(...times);
  const medianS = median(times);
  const deviations = times.map((t) => Math.abs(t - medianS));
  const madS = median(deviations);
  const consistencyPct = Math.max(0, Math.min(100, 100 - ((medianS - bestS) / bestS) * 100 * 4));

  const insights: ConsistencyInsight[] = [];

  // Trend across the run: first-half vs second-half median.
  const half = Math.floor(times.length / 2);
  if (half >= 2) {
    const firstHalf = median(times.slice(0, half));
    const secondHalf = median(times.slice(times.length - half));
    if (secondHalf < firstHalf - 0.15) {
      insights.push({
        id: "improving",
        title: "Getting faster through the run",
        detail: `Typical lap improved ${(firstHalf - secondHalf).toFixed(2)} s from the first half to the second — tyres coming in, or the driver building up. Good sign; log what changed.`,
      });
    } else if (secondHalf > firstHalf + 0.25) {
      insights.push({
        id: "fading",
        title: "Lap times fading late in the run",
        detail: `Typical lap slowed ${(secondHalf - firstHalf).toFixed(2)} s in the second half. Common causes: tyres past their window (pressures too high), driver fatigue, or sliding as grip drops. Check hot pressures and tyre temps next stop.`,
      });
    }
  }

  // One-off spike laps (traffic / mistake) vs genuine inconsistency.
  const spikes = times.filter((t) => t > medianS + Math.max(0.8, 3 * (madS || 0.2))).length;
  if (spikes > 0 && spikes <= Math.ceil(times.length / 4)) {
    insights.push({
      id: "spikes",
      title: `${spikes} slow outlier lap${spikes > 1 ? "s" : ""}`,
      detail: "A few laps are far off the median — usually traffic or a single mistake, not setup. Judge the session by the median, not the worst lap.",
    });
  }

  if (consistencyPct != null && consistencyPct >= 85) {
    insights.push({
      id: "consistent",
      title: "Consistent session",
      detail: `Median lap is within ${(medianS - bestS).toFixed(2)} s of the best. With laps this repeatable, a single setup change will show up clearly next run — change ONE thing.`,
    });
  } else if (consistencyPct != null && consistencyPct < 60) {
    insights.push({
      id: "inconsistent",
      title: "Laps vary a lot",
      detail: `Median is ${(medianS - bestS).toFixed(2)} s off the best lap. Before touching the kart, work on hitting the same marks every lap — setup changes cannot be read against inconsistent laps.`,
    });
  }

  return { lapCount: times.length, bestS, medianS, madS, consistencyPct, insights };
}

/** Compact per-lap table rows for the upload screen. */
export function lapTableRows(
  analysis: LoggerAnalysis,
): { lap: number; time: string; deltaToBest: string; topSpeed: string; minSpeed: string }[] {
  const best = analysis.bestLapIndex != null ? analysis.laps[analysis.bestLapIndex] : null;
  return analysis.laps.map((lap: LoggerLap) => ({
    lap: lap.index,
    time: formatLapTime(lap.timeS),
    deltaToBest: best ? `+${Math.max(0, lap.timeS - best.timeS).toFixed(3)}` : "—",
    topSpeed: lap.maxSpeedKmh != null ? `${lap.maxSpeedKmh.toFixed(0)} km/h` : "—",
    minSpeed: lap.minSpeedKmh != null ? `${lap.minSpeedKmh.toFixed(0)} km/h` : "—",
  }));
}
