/** Extra unique Australian / pathway trivia for AUS_Q&A merge. */

function q(question, correct, wrongs, joke, rating) {
  const options = [correct, ...wrongs.slice(0, 3), joke].filter((s) => typeof s === 'string' && s.length > 0);
  return {
    question,
    options,
    correct_index: 0,
    difficulty_rating: rating,
    difficulty: rating <= 4 ? 'easy' : 'hard',
    source: 'au-extra',
  };
}

export const AU_EXTRA_TRIVIA = [
  q("What does AKC stand for?", "Australian Kart Championship", ["Australian Kart Club","Asian Kart Cup","Adelaide Kart Circuit"], "A Kangaroo Convention", 1),
  q("What does KA stand for?", "Karting Australia", ["Karting Association only","Kids Autocross","Karting Asia"], "Kettle Appreciation", 1),
  q("What portal do Australian karters use to join a club?", "KOMP (portal.karting.net.au)", ["MyLaps only","Motorsport Australia CAMS","iRacing"], "The school intranet", 2),
  q("Who publishes the Australian Karting Manual?", "Karting Australia", ["FIM","Supercars Australia","FIA only"], "The local fish-and-chip shop", 2),
  q("What engine do Cadet 9 and Cadet 12 share?", "Vortex Mini Rok", ["IAME X30","Rotax Senior Max","Torini TC210"], "A hairdryer", 2),
  q("What restrictor does Cadet 9 use in the 2026 book?", "16 mm", ["19 mm","22 mm","None"], "A drinking straw", 3),
  q("What sealed four-stroke is used in 4SS?", "Torini Clubmaxx TC210", ["KA100","KZ2","Mini Rok"], "A lawnmower from Bunnings", 2),
  q("Who imports IAME in Australia?", "Remo Racing", ["OTK Kart Group","IKD only","DPE"], "The pie van", 3),
  q("Who is the Australian Rotax channel in the research set?", "International Karting / IKD", ["Remo Racing","Parolin Australia","Torini"], "A ferry company", 3),
  q("Which OTK brands are listed together for Australia?", "Tony Kart, Kosmic and LN Kart", ["Birel, CRG and Arrow","Parolin, EOS and DAP","FA Kart and KR only"], "Lego, Duplo and Knex", 3),
  q("Which shop is listed for Arrow, FA Kart, KR and DAP?", "DPE Kart Superstore", ["Remo Racing","OTK Kart Group","Torini"], "The servo fridge", 3),
  q("Where was 2026 AKC Round 1 listed?", "Coffs Harbour / C.ex Raceway", ["Phillip Island","Bathurst","The Bend car circuit"], "A Bunnings car park", 2),
  q("Where was 2026 AKC Round 2 listed?", "Ipswich Kart Club", ["Bolivar","Seymour","Townsville"], "The moon base", 2),
  q("Where was 2026 AKC Round 5 listed?", "Bolivar / Southern Go Kart Club", ["Coffs Harbour","Ipswich","Seymour"], "Narnia", 2),
  q("Which state is Eastern Lions Kart Club in?", "Victoria", ["NSW","QLD","SA"], "Middle-earth", 2),
  q("Which state is Coffs Harbour Kart Racing Club in?", "New South Wales", ["Queensland","Victoria","WA"], "Atlantis", 1),
  q("Which state is Ipswich Kart Club in?", "Queensland", ["NSW","SA","WA"], "The Antarctic", 1),
  q("Which state is Southern Go Kart Club (Bolivar) in?", "South Australia", ["Victoria","WA","NT"], "The Shire", 1),
  q("What venue name is used for Eastern Creek karting in KartRacer?", "Sydney International Karting Raceway", ["Sydney Motorsport Park Gardner GP","Wakefield Park","One Raceway"], "Westfield food court", 4),
  q("CHKRC in the GPX set is which club?", "Coffs Harbour Kart Racing Club", ["Coffs Harbour Motorcycle Club","Canberra Kart Club","Club SA"], "A radio station", 3),
  q("ClubSA / Monarto in the GPX set is which club?", "Go Kart Club of SA", ["Southern Go Kart Club only","Whyalla Kart Club","Barossa Kart Club"], "A footy club", 4),
  q("Is GoK World the same as Newcastle Kart Racing Club?", "No", ["Yes","Only on Sundays","They share one licence"], "They are the same pizza shop", 4),
  q("Which Victorian started in karts and reached Formula 1 at McLaren?", "Oscar Piastri", ["Daniel Ricciardo","Mark Webber","Jack Doohan"], "Crocodile Dundee", 2),
  q("Which F1 driver started at Tiger Kart Club in WA?", "Daniel Ricciardo", ["Oscar Piastri","Jack Doohan","Mark Webber"], "The Honey Badger’s dentist", 2),
  q("Which Australian is listed as an AKC graduate who reached F1?", "Jack Doohan", ["Mick Doohan","Wayne Gardner","Casey Stoner"], "A lawnmower champion", 3),
  q("Which Toowoomba karter later won the Indianapolis 500?", "Will Power", ["Scott McLaughlin","Ryan Briscoe","Scott Dixon"], "A power-bill mascot", 3),
  q("Which NZ karter won Supercars titles and also raced IndyCar?", "Scott McLaughlin", ["Shane van Gisbergen","Scott Dixon","Earl Bamber"], "A sheep shearer", 3),
  q("Which Gold Coast karter moved into Triple Eight Supercars?", "Broc Feeney", ["Will Brown","Cam Waters","Chaz Mostert"], "A surf lifesaver", 3),
  q("Which Mildura karter became a Supercars race winner?", "Cam Waters", ["David Reynolds","Garth Tander","James Courtney"], "A grape farmer", 3),
  q("Which NZ karter won Supercars titles then raced NASCAR?", "Shane van Gisbergen", ["Scott McLaughlin","Scott Dixon","Brendon Hartley"], "A kiwi fruit", 3),
  q("Which Sunshine Coast karter reached Porsche and Le Mans?", "Matt Campbell", ["Earl Bamber","Brendon Hartley","Will Power"], "A pineapple", 4),
  q("Which Tasmanian karter won Supercars then raced NASCAR?", "Marcos Ambrose", ["Jamie Whincup","Craig Lowndes","Garth Tander"], "A devil", 4),
  q("Which Sydney karter reached IndyCar?", "Ryan Briscoe", ["Will Power","Mark Webber","Oscar Piastri"], "A ferry captain", 4),
  q("Which Queanbeyan racer reached Formula 1?", "Mark Webber", ["Oscar Piastri","Jack Doohan","Daniel Ricciardo"], "A public-servant kart", 4),
  q("What is the usual single-seater path after karting toward F1?", "Formula 4, then F3, then F2", ["Supercars, then NASCAR","Indy NXT only","GT3 only"], "Mario Kart, then F-Zero", 3),
  q("What is F1 Academy?", "A single-seater series for women toward Formula 1", ["A kart-only junior cup","A Supercars support class","A NASCAR truck series"], "A homework club", 3),
  q("Which Australian is listed with an F1 Academy pathway (grid VERIFY)?", "Aiva Anagnostiadis", ["Oscar Piastri","Broc Feeney","Will Power"], "A soap-opera extra", 4),
  q("What does TaG stand for in karting?", "Touch and Go", ["Track and Grip","Two and Gear","Timed Autocross Group"], "Tea and Ginger", 2),
  q("What extra brakes does KZ2 have versus a typical sprint kart?", "Front brakes", ["No brakes","Inboard motorcycle discs","ABS"], "A handbrake from a ute", 3),
  q("What fuel style is listed for 4SS / Torini?", "PULP (sealed four-stroke)", ["Avgas only","E85 only","Methanol only"], "Chocolate milk", 4),
  q("What dry tyre is listed for Cadet 9/12 in the 2026 table?", "Maxxis 190D", ["LeCont LH03","LeCont LPM","Mojo D5 only"], "A bicycle slick", 3),
  q("What wet tyre is listed for Cadets in the 2026 table?", "Maxxis MW21", ["LeCont SV1 only","Pirelli rain","Dunlop KR"], "Gumboots", 3),
  q("What LeCont dry is cited for KA3 / KA4 / TaG Restricted?", "LH03", ["LOH","LPM","SV1"], "A pizza topping", 4),
  q("What LeCont dry is cited for KA2 / TaG 125?", "LOH", ["LH03","LPM","MW21"], "A radio station", 4),
  q("What LeCont dry is cited for X30 / Rok GP / KZ2?", "LPM", ["LH03","LOH","190D"], "A lunch special", 4),
  q("What cold-pressure start is cited for Maxxis Cadet M190D?", "0.6 bar (about 8.7 psi)", ["1.4 bar","20 psi","0.2 bar"], "Whatever the compressor feels", 4),
  q("What LH03 cold-pressure start window is cited?", "9.5–11.0 psi", ["6–7 psi","15–18 psi","0.3 bar only"], "A lucky number", 4),
  q("Should you invent a race pressure if the spec paper is missing?", "No — say so and cite the KA extract", ["Yes, use 12 psi","Copy F1 blankets","Use car psi"], "Ask a magician", 3),
  q("What is the first cheap setup change in the coach pack?", "Tyre pressures", ["New axle","New chassis","Cut the seat"], "Paint the kart pink", 2),
  q("About how much chain slack is the KB baseline?", "About 10 mm total", ["Zero — run it tight","50 mm","One full link hanging"], "A banana", 3),
  q("What typical front sprocket range does KartRacer use?", "10–11 teeth", ["15–17 teeth","40–45 teeth","6 teeth"], "A pizza cutter", 3),
  q("What typical rear sprocket range does KartRacer use?", "About 68–95 teeth", ["30–40 teeth","12–15 teeth","120–140 teeth"], "A clock face", 3),
  q("What wet gearing start is in the setup notes?", "+3 rear teeth", ["-5 rear teeth","Change the front only","No change"], "Add a bicycle gear", 4),
  q("Do sprint karts have motorcycle-style suspension?", "No — live axle, no springs", ["Yes, forks and a shock","Only the front","Only in rain"], "They bounce on jelly", 2),
  q("What does a yellow flag mean?", "Slow, no overtaking in that sector", ["Race is finished","Last lap","Pit now for fuel"], "Wave at your mum", 1),
  q("What does a red flag mean?", "Stop racing and follow officials", ["Push harder","Last lap","Safety car only"], "Pizza is here", 1),
  q("What does a blue flag mean?", "Faster kart approaching", ["Your race is over","Wet declared","Technical infringement"], "You dropped an ice cream", 2),
  q("What does a black flag mean?", "Report to officials", ["You won","Track is dry","Start your engine"], "Go buy merch", 2),
  q("What is hop in a kart?", "Inside-rear bounce from live-axle bind", ["A jump on the kerb only","Engine misfire","A good start"], "A bunny on the infield", 4),
  q("What is the karting-to-Supercars idea in the pack?", "Karts, then Super3/Super2, then Supercars", ["Karts straight to Bathurst 1000","Karts to MotoGP","Karts to WRC"], "Karts to the school bus", 3),
  q("Which series includes the 24 Hours of Le Mans?", "FIA WEC", ["IndyCar","NASCAR Cup","AKC"], "The school fete", 2),
  q("Which US series includes the Indianapolis 500?", "IndyCar", ["NASCAR Cup","Formula 1","Supercars"], "Monster Jam", 1),
  q("Which US series is stock-car oval racing’s top level?", "NASCAR Cup Series", ["IndyCar","WEC","F1 Academy"], "Demolition derby", 2),
  q("Where did Lewis Hamilton start racing as a kid?", "Karts in Stevenage", ["F2 in Spain","NASCAR trucks","Isle of Man TT"], "A London bus", 3),
  q("Where did Max Verstappen start racing?", "Karts from age four", ["F3 only","Dakar","Moto3"], "A playground swing", 2),
  q("Where did Ayrton Senna become a champion before F1?", "Brazilian karting", ["Indy Lights","NASCAR","Touring cars"], "Beach football", 3),
  q("Which club scene is linked to Schumacher and Vettel in the blurbs?", "Kerpen", ["Monza kart only","Suzuka","Silverstone GP"], "A pretzel factory", 4),
  q("Which NZ karter became a six-time IndyCar champion?", "Scott Dixon", ["Scott McLaughlin","Earl Bamber","Brendon Hartley"], "A hobbit", 4),
  q("Which Spanish karter became an IndyCar champion in the onboarding set?", "Alex Palou", ["Carlos Sainz","Fernando Alonso","Charles Leclerc"], "A tapas chef", 4),
  q("Which seven-time Supercars champion started in karts?", "Jamie Whincup", ["Craig Lowndes","Garth Tander","Marcos Ambrose"], "A cricket captain", 4),
  q("What meeting document can change class weights on the day?", "Supplementary Regulations", ["A Facebook comment","A tyre sticker","The weather app"], "A text from your uncle", 3),
  q("What must D Grade and 8-Day licence holders show?", "A P plate after the Observed Driving Session", ["A gold helmet","A transponder they own","A wet tyre"], "A learner magnet", 4),
  q("Who holds a Participant’s Licence for an under-18 driver?", "A parent or guardian", ["The clerk of course","The engine builder","Any mechanic"], "The family dog", 2),
  q("What is the national combined calendar page named in the handoff?", "karting.net.au/ka-calendar", ["motogp.com","supercars.com","worldsbk.com"], "A secret Facebook group", 3),
  q("Which headline RSS is the primary AU kart feed (probed 2026-09-10)?", "KartSportNews", ["TKART (403)","FIA Karting HTML page","ASBK news"], "A fishing blog", 3),
  q("Why was TKART dropped as a headline source?", "The feed returned 403", ["It is about cars","It is not RSS ever","It is paywalled PDF only"], "They only write in semaphore", 5),
  q("Which 2026 AKC round is listed for Townsville?", "Round 3, 3–5 July 2026 (provisional venue note)", ["Round 1","Round 5","There is no QLD round"], "A cruise ship", 5),
  q("Which 2026 AKC round is listed for Seymour / Eastern Lions?", "Round 4, 4–6 September 2026", ["Round 2","Round 1","Round 5"], "A sheep show", 5),
  q("What KA3 Senior Light example weight is in the 2026 table?", "150 kg kart + driver + equipment", ["110 kg kart only","200 kg driver only","80 kg"], "A bag of potatoes", 5),
  q("What licence grade does National Cadet / KA3 need in the 2026 snapshot?", "C Grade", ["E Grade only","A Grade only","No licence"], "A library card", 5),
  q("What licence grade do KA2, Junior Max, TaG 125 and X30 need?", "B Grade", ["D Grade","8-Day only","E Grade"], "A bus ticket", 5),
  q("How many endorsed meetings move D Grade to C Grade?", "Four", ["One","Twelve","Twenty"], "Until the canteen closes", 5),
  q("What Mini Rok peak figure is cited from vortex-engines.com?", "10 hp at 11,000 rpm", ["30 hp at 11,500","40 hp gearbox","2 hp"], "A blender", 6),
  q("What Rotax Senior MAX EVO power is cited from rotax-racing.com?", "30 hp (22 kW) at 11,500 rpm", ["10 hp","15 hp KA100 only","50 hp"], "A leaf blower", 6),
  q("What X30 power band is cited from AU importer sheets?", "About 30 hp at ~11,000–11,250 rpm", ["10 hp","40+ hp VERIFY KZ","5 hp"], "A kitchen mixer", 6),
  q("What Torini TC210 power is cited from the homologation sheet?", "10 hp at 5,600 rpm", ["30 hp","15 hp at 9,750","40 hp"], "A ceiling fan", 6),
  q("Why is Rok DVS omitted from kartEngineRef.json?", "The hp/rpm pairing is still VERIFY", ["It is banned forever","It is a motorcycle","It has no clutch"], "It failed a spelling test", 6),
  q("Why is KZ2 engine make omitted from kartEngineRef.json?", "Homologated make power is still VERIFY", ["KZ2 is not a kart","It is Cadet only","KA banned it in 1990"], "The gearbox ate the datasheet", 6),
  q("What pyrometer optimum band is cited in the chassis KB?", "About 75–85 °C", ["20–30 °C","120–140 °C","0 °C"], "Room temperature tea", 5),
  q("What pressure step limit does the coach pack use?", "≤0.1 bar per step", ["1.0 bar jumps","5 psi every lap","No limit"], "Until it pops", 6),
  q("Which file is the cited tyre-spec extract?", "gpt-knowledge/control-tyre-data-extract.md", ["A Reddit thread","A Facebook comment","TKART 403 feed"], "A shopping docket", 6),
  q("Which structured snapshot holds 2026 KA classes and weights?", "kb-au-rules/data/classes.json", ["Send-It MoMS index","ASBK tech bulletin","FIM road-race GCR"], "A café menu", 5),
  q("What Rotax Junior MAX EVO power is cited from rotax-racing.com?", "23 hp (17 kW) at 8,500 rpm", ["30 hp at 11,500","10 hp Mini Rok","40 hp KZ VERIFY"], "A desk fan", 6),
  q("What Junior MAX restrictor id family is pointed at in kb-au-rules?", "SR4 23.5 mm (confirm restrictors.json)", ["Cadet 16 mm Mini Rok","KA4 19 mm","No restrictor ever"], "A garden hose", 7),
  q("What KA4 restrictor size does the 2026 book use in the handoff?", "19 mm", ["16 mm Cadet","22 mm only","Open"], "A bottle cap", 6),
  q("What KA3 Junior restrictor size does the 2026 book use in the handoff?", "22 mm", ["16 mm","19 mm only","None"], "A doughnut", 6),
  q("What sign-off must KartRacer Coach use?", "KartRacer Coach", ["RoadRacer AI Coach","Send-It Coach","MoMS Steward"], "A lucky dip", 5),
];

